name: home-dns

services:
  home-dns-node-service:
    container_name: home-dns-node-container
    pull_policy: missing
    build:
      context: .
      no_cache: true
      dockerfile_inline: |
        FROM node:lts-slim
        USER root
        RUN apt-get update -y
        RUN apt-get install ufw -y
        RUN ufw allow 53/udp
        RUN ufw allow 53/tcp
        RUN yarn global add pm2
        COPY dist /dist
        COPY pm2.environment.config.js /pm2.environment.config.js
        CMD pm2-runtime pm2.environment.config.js
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s
    ports:
      - 53:53/udp
      - 53:53/tcp
