name: home_dns

services:
  node:
    container_name: node_container
    pull_policy: missing
    build:
      context: .
      no_cache: true
      dockerfile_inline: |
        FROM node:lts-slim
        RUN apt-get update -y
        RUN apt-get install dnsutils -y
        COPY dist /dist
        CMD node --harmony /dist/core.bundle.js
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s
    ports:
      - 53:53/udp
      - 53:53/tcp
