name: home-dns

services:
  node-service:
    container_name: node-container
    pull_policy: missing
    healthcheck:
      test: 'nslookup -timeout=5 google.com 127.0.0.1'
      interval: 15m
      timeout: 30s
      retries: 5
      start_period: 5s
      start_interval: 0s
    build:
      context: .
      dockerfile_inline: |
        FROM node:lts-slim
        WORKDIR /home-dns
        USER root
        RUN apt-get update -y
        RUN apt-get install ufw dnsutils -y
        RUN ufw allow 53/udp
        RUN ufw allow 53/tcp
        RUN yarn global add pm2
        ADD 'https://www.random.org/integers/?num=1&min=1&max=100000&col=1&base=10&format=plain&rnd=new' /random.org.txt
        COPY . .
        RUN yarn build
        CMD pm2-runtime pm2.environment.config.js
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 30s
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - logs-volume:/home-dns/.logs
      - storage-volume:/home-dns/.storage
volumes:
  logs-volume: {}
  storage-volume: {}
